global:
  scrape_interval: 5s
  evaluation_interval: 5s
rule_files:
 - /etc/prometheus/rules.yml
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: ['prometheus-alertmanager.deti', 'alertmanager:9093']

scrape_configs:

  - job_name: 'postgres-exporter'                                             
    static_configs:                                                                        
    - targets: ['gic7-pg-exporter.pt']
    metrics_path: "/metrics"

  - job_name: 'traefik-metrics'
    static_configs:
    - targets: ['traefik.deti:9100']
    metrics_path: "/metrics"

  - job_name: 'advanced-federation'
    scrape_interval: 25s
    scrape_timeout: 20s
    scheme: http
    metrics_path: /federate
    honor_labels: true
    params:
      match[]:
        - '{__name__=~"kube_.*|node_.*|container_.*|job:.*"}'
    static_configs:
      - targets: ['prometheus.deti']

