apiVersion: v1
kind: Service
metadata:
  name: postgres-master
  namespace: gic7
spec:
  type: NodePort
  selector:
    app: postgres-master
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432