apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-master
  namespace: gic7
  labels:
    component: postgres-master
spec:
  selector:
    matchLabels:
      app: postgres-master
      component: postgres-master
  serviceName: postgres-master
  template:
    metadata:
      labels:
        type: deployment
        app: postgres-master
        component: postgres-master
    spec:
      containers:
        - name: postgres
          image: postgres:11
          command:
            [
              "sh",
              "-c",
              "docker-entrypoint.sh -c config_file=/var/config/postgresql.conf -c hba_file=/var/config/pg_hba.conf",
            ]
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: frs
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: POSTGRES_USER
              value: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data-master
              subPath: postgres
            - mountPath: /var/config
              name: postgres-master-configmap
      volumes:
        - name: postgres-master-configmap
          configMap:
            name: postgres-master-configmap
        - name: postgres-data-master
          persistentVolumeClaim:
            claimName: postgres-data-master