apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-master
  namespace: gic7
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi