
# Create front end deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: detectron-fe-deployment
  namespace: gic7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detectron-fe
  strategy: {}
  template:
    metadata:
      labels:
        app: detectron-fe
    spec:
      containers:
        - image: registry.deti:5000/detectron-fe
          name: detectron-fe
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always     

# Create Service for front end
---
apiVersion: v1
kind: Service
metadata:
  name: detectron-fe-service
  namespace: gic7
spec:
  ports:
  - port: 8000
    targetPort: 80
  selector:
    app: detectron-fe