apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: detectron-db-data
  namespace: gic7
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
