server:
  port: ${API_PORT:8080}

spring:
  liquibase:
    enabled: false # we have transitive liquibase dependencies in classpath, but no migrations exists for 'api' app
  profiles:
    active: prod

---

spring:
  cache:
    jcache:
      config: classpath:ehcache.xml

  jackson:
    serialization:
      indent-output: true
  datasource-pg:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL:jdbc:postgresql://my-release-postgresql-ha-pgpool:5432/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 3
      minimum-idle: 3
      data-source-properties:
        stringtype: unspecified
  jpa:
    properties:
      hibernate:
        default_schema: public
        jdbc.lob.non_contextual_creation: true # fix for Caused by: java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
    database: postgresql
    open-in-view: true
    generate-ddl: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

# "environment" and "image" blocks should be same in those files:
#    * api/src/main/resources/application.properties
#    * admin/src/main/resources/application.properties

environment:
  servers:
    PYTHON:
      url: ${PYTHON_URL:http://detectron-core-service:3000}

image:
  types:
    - tif
    - tiff
    - jpg
    - jpeg
    - png
    - bmp
    - ico
    - gif
    - webp
  saveImagesToDB: ${SAVE_IMAGES_TO_DB:true}

app:
  feign:
    appery-io:
      url: https://api.appery.io/rest/1/db/collections
      api-key: ${APPERY_API_KEY:#{null}}

---

spring:
  profiles: dev
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
#  datasource-pg:
#    url: jdbc:postgresql://hrkv042.kh.exadel.ua:6432/frs
#    username: postgres
#    password: postgres

swagger:
  info:
    title: CompreFace - API
    version: 0.0.2-SNAPSHOT