# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Step to create Docker images for each componenet
      - name: Build Docker images
        run: |
          
          whoami
          # Fe Image
          cd ~/actions-runner/_work/GIC_Detectron/GIC_Detectron/ui
          docker build -f docker-prod/Dockerfile . --tag registry.deti:5000/detectron-fe
          
          # Api and Admin Server Image
          cd ~/actions-runner/_work/GIC_Detectron/GIC_Detectron/java
          docker build -f ../dev/Dockerfile . -t build --target build
          docker build -f ../dev/Dockerfile . -t registry.deti:5000/detectron-api --target frs_core
          docker build -f ../dev/Dockerfile . -t registry.deti:5000/detectron-admin --target frs_crud
          
          # Embedding Servers Image
          cd ~/actions-runner/_work/GIC_Detectron/GIC_Detectron/embedding-calculator
          docker build . --tag registry.deti:5000/detectron-core
          
          # Static Website Image
          cd ~/actions-runner/_work/GIC_Detectron/GIC_Detectron/static-website
          docker build . -t registry.deti:5000/detectron-static-web

          
      # Step to push Docker images for each component
      - name: Push docker images
        run: |
          # Push Fe Image
          docker push registry.deti:5000/detectron-fe
          
          # Push Admin Server Image
          docker push registry.deti:5000/detectron-admin
          
          # Push Api Server Image
          docker push registry.deti:5000/detectron-api
          
          # Push Embedding Servers Image 
          docker push registry.deti:5000/detectron-core
          
          # Push Static Website Image
          docker push registry.deti:5000/detectron-static-web
      
      # Step to apply configurations in Kubernetes Cluster
      - name: Apply configurations
        run: |
          kubectl apply -f kubernetes/admin.yaml
          kubectl apply -f kubernetes/api.yaml
          kubectl apply -f kubernetes/core.yaml
          kubectl apply -f kubernetes/fe.yaml
          kubectl apply -f kubernetes/ingress.yaml
          kubectl apply -f kubernetes/secrets.yaml
          kubectl apply -f static-website/kubernetes/webpage.yaml 
      
      # Restart pods to get the updated images
      - name: Reload pods
        run: |
          kubectl rollout restart deployment detectron-fe-deployment -n gic7
          kubectl rollout restart deployment detectron-admin-deployment -n gic7
          kubectl rollout restart deployment detectron-api-deployment -n gic7
          kubectl rollout restart deployment detectron-core-deployment -n gic7
          kubectl rollout restart deployment detectron-static-deployment -n gic7
